// Turn the plain web export into something that installs on a phone.
//
// Three jobs, all after the fact so none of them touch app.json and change the
// native runtime fingerprint:
//
//  1. Rewrite the absolute paths Expo emits to relative ones, so the app works
//     from a subfolder — which is where GitHub Pages serves it.
//  2. Inject the manifest link, the meta tags iOS needs before Safari will put
//     it on a home screen as an app rather than a bookmark, and the description
//     and Open Graph tags a shared link needs before it shows as anything but
//     a bare URL.
//  3. Write a service worker that precaches every file in the build, so it
//     opens with no signal. A calculator that needs a bar of service is no use
//     in a basement, and basements are where the pipe is.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';

const dist = process.argv[2] ?? 'dist';

// One line, in the three places somebody meets the app before they open it:
// the install prompt, a shared link's card, and a search result. It is not put
// on a screen inside the app — a tagline shown to somebody who already
// installed it is an advertisement they cannot act on.
const TAGLINE = 'The only one an industrial fitter needs.';

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });

// Everything shipped, minus the files that only describe the build.
const SKIP = new Set(['metadata.json', 'sw.js']);
const files = walk(dist)
  .map((f) => relative(dist, f).split(sep).join(posix.sep))
  .filter((f) => !SKIP.has(f))
  .sort();

const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);

// --- 0: the asset paths baked into the bundle ---
//
// Expo writes every font and image into the bundle as "/assets/...", rooted at
// the domain. Served from a folder — which is what GitHub Pages and most free
// hosting give you — every one of them 404s, and the app comes up with no
// icons and the fallback serif. Making them relative costs nothing at the root
// and is the difference between working and not anywhere else.
const jsDir = join(dist, '_expo', 'static', 'js', 'web');
let rewritten = 0;
for (const name of readdirSync(jsDir)) {
  if (!name.endsWith('.js')) continue;
  const path = join(jsDir, name);
  const before = readFileSync(path, 'utf8');
  const after = before.replace(/(["'])\/assets\//g, '$1assets/');
  if (after !== before) {
    writeFileSync(path, after);
    rewritten += (before.match(/["']\/assets\//g) ?? []).length;
  }
}

// --- 1 and 2: the page itself ---
const htmlPath = join(dist, 'index.html');
let html = readFileSync(htmlPath, 'utf8');

html = html.replace(/(src|href)="\/(?!\/)/g, '$1="./');

const head = `
    <base href="./" />
    <link rel="manifest" href="./manifest.webmanifest" />
    <meta name="theme-color" content="#11447E" />
    <meta name="description" content="${TAGLINE} Calculators, spools and the handbook, offline." />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />
    <meta name="apple-mobile-web-app-title" content="PipeFit Pro" />
    <link rel="apple-touch-icon" href="./apple-touch-icon.png" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="PipeFit Pro" />
    <meta property="og:description" content="${TAGLINE} Calculators, spools and the handbook, offline." />
    <meta property="og:image" content="./icon-512.png" />
    <meta name="twitter:card" content="summary" />
  `;
html = html.replace('</head>', `${head}</head>`);

const register = `
    <script>
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () {
          navigator.serviceWorker.register('./sw.js').catch(function () {});
        });
      }
    </script>
  `;
html = html.replace('</body>', `${register}</body>`);
writeFileSync(htmlPath, html);

// --- 3: the service worker ---
const sw = `// Generated by tools/pwa.mjs. Do not edit.
const CACHE = 'pipefit-${version}';
const FILES = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;

  // Opening the app offline has to land on the shell, whatever the address bar
  // says, because the whole app lives behind one page.
  if (e.request.mode === 'navigate') {
    e.respondWith(caches.match('./').then((hit) => hit || fetch(e.request)));
    return;
  }

  e.respondWith(
    caches.match(e.request).then(
      (hit) =>
        hit ||
        fetch(e.request).then((res) => {
          if (res && res.ok && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy));
          }
          return res;
        })
    )
  );
});
`;
writeFileSync(join(dist, 'sw.js'), sw);

console.log(`pwa: ${rewritten} asset paths made relative, ${files.length} files precached, cache pipefit-${version}`);
